# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='./companylogos/')),
                ('segment', models.CharField(choices=[('BRK', 'Broker'), ('MFT', 'Manufacturer'), ('MKG', 'Marketing Authorisation Holder'), ('HSP', 'Hospital'), ('PHA', 'Pharmacy'), ('WHL', 'Wholesaler')], default='WHL', max_length=3)),
                ('co_number', models.IntegerField(blank=True, null=True)),
                ('tel_number', models.IntegerField(blank=True, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(blank=True, max_length=7, null=True)),
                ('country', models.CharField(choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('UK', 'United Kingdom')], default='UK', max_length=3)),
                ('website', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MAL', 'Male'), ('FEM', 'Female')], default='MAL', max_length=3)),
                ('picture', models.ImageField(blank=True, upload_to='./profilepics/')),
                ('user_type', models.CharField(choices=[('PHA', 'Pharmacy'), ('WHL', 'Wholesaler')], default='WHL', max_length=3)),
                ('country', models.CharField(choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('UK', 'United Kingdom')], default='UK', max_length=3)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
