# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('SWZ', 'Switzerland'), ('UK', 'United Kingdom')], default='UK', max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('SWZ', 'Switzerland'), ('UK', 'United Kingdom')], default='UK', max_length=3),
        ),
    ]
