# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170716_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='picture',
        ),
    ]
