# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170717_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='picture',
            field=models.ImageField(blank=True, upload_to='productpics'),
        ),
    ]
