# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170725_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('SWZ', 'Switzerland'), ('UK', 'United Kingdom')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAL', 'Male'), ('FEM', 'Female')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('PHA', 'Pharmacy'), ('WHL', 'Wholesaler')], max_length=3),
        ),
    ]
