# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 08:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170801_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_created',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='on_floor',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='product_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
