# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20170801_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='coa',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='delivery',
            field=models.CharField(choices=[('DEL', 'Delivery Price'), ('FOC', 'FOC'), ('EXW', 'Ex-Works')], default='DEL', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='origin',
            field=models.CharField(blank=True, choices=[('FRA', 'France'), ('GER', 'Germany'), ('SPA', 'Spain'), ('SWZ', 'Switzerland'), ('UK', 'United Kingdom')], max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
