# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20170801_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='barcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
