# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_listing_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='firstname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='secondname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
