# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20170823_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Below Average'), (3, '3 - Average'), (4, '4 - Great'), (5, '5 - Oustanding')], default=1, null=True),
        ),
    ]
