# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170902_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
